import type { Locale } from "@workspace/lib/locales";
import type { Workflow } from "./workflows";
export const workflowLabels: Record<Locale, Record<Workflow, string>> = {
  en: {
    "video-review": "Video evidence review",
    "trusted-voice-review": "Trusted voice policy",
    "advisor-review": "Cross-domain advisor",
    "legacy-review": "Legacy review",
    "identity-review": "Identity review",
    "phishing-review": "Email review",
    "qr-review": "QR review",
    "call-review": "Call transcript review",
    "document-review": "Document review",
    "recovery-review": "Recovery review",
    "policy-review": "Approval policy review",
    "simulation-review": "Practice debrief",
  },
  es: {
    "video-review": "Revisión de vídeo",
    "trusted-voice-review": "Política de voz de confianza",
    "advisor-review": "Asesor multidominio",
    "legacy-review": "Revisión sucesoria",
    "identity-review": "Revisión de identidad",
    "phishing-review": "Revisión de correo",
    "qr-review": "Revisión QR",
    "call-review": "Revisión de transcripción",
    "document-review": "Revisión documental",
    "recovery-review": "Revisión de recuperación",
    "policy-review": "Revisión de aprobaciones",
    "simulation-review": "Análisis de práctica",
  },
  de: {
    "video-review": "Videobelegprüfung",
    "trusted-voice-review": "Richtlinie für vertraute Stimmen",
    "advisor-review": "Bereichsübergreifende Beratung",
    "legacy-review": "Nachlassprüfung",
    "identity-review": "Identitätsprüfung",
    "phishing-review": "E-Mail-Prüfung",
    "qr-review": "QR-Prüfung",
    "call-review": "Transkriptprüfung",
    "document-review": "Dokumentenprüfung",
    "recovery-review": "Wiederherstellungsprüfung",
    "policy-review": "Freigaberichtlinienprüfung",
    "simulation-review": "Übungsnachbesprechung",
  },
  fr: {
    "video-review": "Examen des preuves vidéo",
    "trusted-voice-review": "Politique de voix de confiance",
    "advisor-review": "Conseil transversal",
    "legacy-review": "Examen successoral",
    "identity-review": "Examen d’identité",
    "phishing-review": "Examen d’e-mail",
    "qr-review": "Examen QR",
    "call-review": "Examen de transcription",
    "document-review": "Examen documentaire",
    "recovery-review": "Examen de récupération",
    "policy-review": "Examen d’approbation",
    "simulation-review": "Bilan d’exercice",
  },
};
export const reviewScopeText: Record<Locale, string> = {
  en: "Verifier reviewed only an excerpt of the findings",
  es: "El verificador solo revisó un extracto de los resultados",
  de: "Der Verifizierer prüfte nur einen Auszug der Ergebnisse",
  fr: "Le vérificateur n’a examiné qu’un extrait des conclusions",
};
